language: python

python:
    - 3.4

sudo: required
dist: trusty
addons:
  firefox: "latest"

before_install:
    - firefox --version
    - export NO_VENV=1
    - make deps
    - make images
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
    - export NO_VENV=1
    - make install

script:
    - export NO_VENV=1
    - make test
    - make docs
    - make db
    - make certs
    - pushd jupyterhub
    - mkdir -p /tmp/remoteapp
    - chmod 755 `pwd`/start.sh
    - "`pwd`/start.sh &"
    - popd
    - sleep 3
    - DISPLAY=:99 python -m unittest discover -s selenium_tests -t . -v

after_success:
    - coverage run -m tornado.testing discover
    - pip install codecov
    - codecov
    - bash <(curl -s https://codecov.io/bash)
