language: python

python:
    - 3.4

sudo: required
dist: trusty

before_install:
    - sudo apt-get update
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
    - sudo pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt
    - pip install -r doc-requirements.txt
install:
    - python setup.py install

script:
    - flake8 .
    - python -m tornado.testing discover -v
    - sphinx-build -W doc/source doc/build/sphinx

after_success:
  - bash <(curl -s https://codecov.io/bash)
