language: python

python:
    - 3.4

sudo: required
dist: trusty

before_install:
    - sudo apt-get update
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
    - sudo pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt
    - pip install -r doc-requirements.txt
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install:
    - python setup.py install

script:
    - flake8 .
    - python -m tornado.testing discover -s tests -v
    - pushd jupyterhub 
    - docker pull simphonyproject/simphonic-mayavi:latest
    - remoteappdb --db=remoteappmanager.db init
    - remoteappdb --db=remoteappmanager.db user create test
    - remoteappdb --db=remoteappmanager.db app create simphonyproject/simphonic-mayavi 
    - remoteappdb --db=remoteappmanager.db app grant simphonyproject/simphonic-mayavi test
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_jupyterhub.pid --make-pidfile --background --exec start.sh" 
    - popd
    - sleep 3
    - python -m unittest discover -s selenium -v
    - sphinx-build -W doc/source doc/build/sphinx

after_success:
    - coverage run -m tornado.testing discover
    - pip install codecov
    - codecov
    - bash <(curl -s https://codecov.io/bash)
